	ORG 0x00
CONT EQU 0x20
CONT1 EQU 0x21
CONT_S EQU 0x22
CONTINI EQU 21

DIGA EQU 0x30
DIGB EQU 0x31
DIGC EQU 0x32
DIGD EQU 0x33




INICIO:
	CLRF DIGA
	CLRF DIGB
	CLRF DIGC
	CLRF DIGD
	
	MOVLW TRISB
    MOVWF FSR
    MOVLW   0XFF
    MOVWF   0           ;SET PORTB AS INPUT
    BSF STATUS, RP0
    BCF OPTION_REG, 7  ;SET PORTB PULL-UP
    BCF STATUS, RP0
    MOVLW TRISD
	MOVWF FSR
	CLRF INDF
	MOVLW TRISA
	MOVWF FSR
	CLRF INDF

CONTA
    	CALL DELAY_1S
	INCF DIGA, F
	MOVLW 10
	SUBWF DIGA, W
	BTFSS STATUS,Z
	GOTO CONTA
	CLRF DIGA
	INCF DIGB, F
	MOVLW 10
	SUBWF DIGB, W
	BTFSS STATUS,Z
	GOTO CONTA
	CLRF DIGB
	INCF DIGC, F
	MOVLW 10
	SUBWF DIGC, W
	BTFSS STATUS,Z
	GOTO CONTA
	CLRF DIGC
	INCF DIGD, F
	MOVLW 10
	SUBWF DIGD, W
	BTFSS STATUS,Z
	GOTO CONTA
	CLRF DIGD
	GOTO CONTA	

MOSTRA            ;45 us de duracao
	MOVFW DIGA    
	CALL DIG      
	MOVWF PORTD   
	BSF PORTA, 5  
	BCF PORTA, 5  
	MOVFW DIGB    
	CALL DIG      
	MOVWF PORTD   
	BSF PORTA, 4  
	BCF PORTA, 4  
	MOVFW DIGC     
	CALL DIG      
	MOVWF PORTD   
	BSF PORTA, 3  
	BCF PORTA, 3  
	MOVFW DIGD    
	CALL DIG      
	MOVWF PORTD   
	BSF PORTA, 2 
	BCF PORTA, 2  
	RETURN	      
		
	
	
	
	
DELAY_MS
	MOVLW CONTINI
	MOVWF CONT
	NOP
	NOP
	NOP
    NOP
    NOP
DELAY_LOOP
    CALL    MOSTRA
    BTFSS   PORTB,  3	;TESTA PELO PAUSE
    CALL    PAUSA
    BTFSS   PORTB,  5	;TESTA PELO ZERAR
    CALL    ZERA
	DECFSZ CONT,F
	GOTO DELAY_LOOP
	RETURN	

DELAY_100MS
	MOVLW 100
	MOVWF CONT1
DELAY_100MS_LOOP
	CALL DELAY_MS
	DECFSZ CONT1,F
	GOTO DELAY_100MS_LOOP	
	RETURN

DELAY_1S
    MOVLW 10
    MOVWF CONT_S
DELAY_1S_LOOP
    CALL DELAY_100MS
    DECFSZ CONT_S,F
    GOTO DELAY_1S_LOOP
    RETURN

PAUSA
    BTFSC   PORTB,  4
    GOTO    PAUSA
    RETURN

ZERA
    CLRF    DIGA
    CLRF    DIGB
    CLRF    DIGC
    CLRF    DIGD
    RETURN

    
DIG	                    ;T=3
        ADDWF	PCL,F	;1
DIG0	RETLW 0x3F      ;2
DIG1	RETLW 0x06
DIG2	RETLW 0x5b
DIG3	RETLW 0x4F
DIG4	RETLW 0x66
DIG5	RETLW 0x6D
DIG6	RETLW 0x7D
DIG7	RETLW 0x07
DIG8	RETLW 0x7F
DIG9	RETLW 0x6F
